// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3MbnrS0FlJRsNlC1Uq9JEf3-aYcsgo5I',
    appId: '1:429098132695:web:4adfd64228a1afcab6bc92',
    messagingSenderId: '429098132695',
    projectId: 'hope-cff1b',
    authDomain: 'hope-cff1b.firebaseapp.com',
    storageBucket: 'hope-cff1b.firebasestorage.app',
    measurementId: 'G-FFLW8YJ6KC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgjdnM9pULpfofkYvN578Id1qVA9BmpxA',
    appId: '1:429098132695:android:b184d582929c892db6bc92',
    messagingSenderId: '429098132695',
    projectId: 'hope-cff1b',
    storageBucket: 'hope-cff1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_LvyJnNmvlCfgnL7bnyBmGPSiPKhuY_k',
    appId: '1:429098132695:ios:05dd587e2d801d51b6bc92',
    messagingSenderId: '429098132695',
    projectId: 'hope-cff1b',
    storageBucket: 'hope-cff1b.firebasestorage.app',
    iosBundleId: 'com.example.hope',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_LvyJnNmvlCfgnL7bnyBmGPSiPKhuY_k',
    appId: '1:429098132695:ios:05dd587e2d801d51b6bc92',
    messagingSenderId: '429098132695',
    projectId: 'hope-cff1b',
    storageBucket: 'hope-cff1b.firebasestorage.app',
    iosBundleId: 'com.example.hope',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3MbnrS0FlJRsNlC1Uq9JEf3-aYcsgo5I',
    appId: '1:429098132695:web:b46a51643ceeeb59b6bc92',
    messagingSenderId: '429098132695',
    projectId: 'hope-cff1b',
    authDomain: 'hope-cff1b.firebaseapp.com',
    storageBucket: 'hope-cff1b.firebasestorage.app',
    measurementId: 'G-3JQYWGN9XL',
  );
}
